# yaml-language-server: $schema=https://json.schemastore.org/none
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: glenntemplate-clone
  title: Clone Glenn's GitHub Template
  description: Clones the glenntemplate repo from gbayareametro
  tags:
    - github
    - template
    - clone
spec:
  owner: user:glennbrown
  type: website
  parameters:
    - title: Repository Info
      description: Repository Information
      required:
        - repoName
        - name

      properties:
        repoName:
          title: Repo Name
          type: string
          description: Git Repository Name
        repoDescription:
          title: Repo Description
          type: string
          description: A Short Description of the Repo
        name:
          title: Your Name
          type: string
          description: Your Name
  steps:
    - id: fetch-template
      name: Fetch Glenn's Template
      action: fetch:template
      input:
        url: https://github.com/gbbayareametro/glenntemplate
        targetPath: .
        values:
          repoName: ${{ parameters.repoName }}
          description: ${{ parameters.description }}
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: github.com?owner=gbbayareametro&repo=${{ parameters.repoName }}
        repoVisibility: public
        description: ${{ parameters.description }}
        defaultBranch: main
        protectDefaultBranch: true
        values:
          name: ${{ parameters.name }}
